# Generated by Django 3.2.2 on 2024-03-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='location_x',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='location_y',
            field=models.TextField(blank=True),
        ),
    ]
