# Generated by Django 3.2.2 on 2024-03-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Rider', 'Rider'), ('Driver', 'Driver'), ('Admin', 'Admin')], default='Rider', max_length=20),
        ),
    ]
