# Generated by Django 3.2.2 on 2024-03-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240317_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
